// All KCLS branch names for Google Places API lookup.
// Update this list if branches are added or removed.
export const KCLS_BRANCHES = [
  "Algona-Pacific Library KCLS",
  "Auburn Library KCLS",
  "Bellevue Library KCLS",
  "Black Diamond Library KCLS",
  "Bothell Library KCLS",
  "Boulevard Park Library KCLS",
  "Burien Library KCLS",
  "Carnation Library KCLS",
  "Covington Library KCLS",
  "Des Moines Library KCLS",
  "Duvall Library KCLS",
  "Enumclaw Library KCLS",
  "Fairwood Library KCLS",
  "Fall City Library KCLS",
  "Federal Way 320th Library KCLS",
  "Federal Way Library KCLS",
  "Issaquah Library KCLS",
  "Kenmore Library KCLS",
  "Kent Library KCLS",
  "Kingsgate Library KCLS",
  "Kirkland Library KCLS",
  "Lake Forest Park Library KCLS",
  "Lake Hills Library KCLS",
  "Library Connection @ Crossroads",
  "Maple Valley Library KCLS",
  "Mercer Island Library KCLS",
  "Muckleshoot Library KCLS",
  "Newcastle Library KCLS",
  "Newport Way Library KCLS",
  "North Bend Library KCLS",
  "Redmond Library KCLS",
  "Renton Library KCLS",
  "Renton Highlands Library KCLS",
  "Richmond Beach Library KCLS",
  "Sammamish Library KCLS",
  "Shoreline Library KCLS",
  "Skykomish Library KCLS",
  "Snoqualmie Library KCLS",
  "Tukwila Library KCLS",
  "Vashon Library KCLS",
  "White Center Library KCLS",
  "Woodinville Library KCLS",
  "Woodmont Library KCLS",
];
