import type { LibrarySystem } from "../src/lib/types";

// All library branch names for Google Places API lookup, organized by system.
// Each branch name includes the system name suffix to help disambiguation.
// Update these lists if branches are added or removed.
export const LIBRARY_BRANCHES: Record<LibrarySystem, string[]> = {
  kcls: [
    "Algona-Pacific Library KCLS",
    "Auburn Library KCLS",
    "Bellevue Library KCLS",
    "Black Diamond Library KCLS",
    "Bothell Library KCLS",
    "Boulevard Park Library KCLS",
    "Burien Library KCLS",
    "Carnation Library KCLS",
    "Covington Library KCLS",
    "Des Moines Library KCLS",
    "Duvall Library KCLS",
    "Enumclaw Library KCLS",
    "Fairwood Library KCLS",
    "Fall City Library KCLS",
    "Federal Way 320th Library KCLS",
    "Federal Way Library KCLS",
    "Greenbridge Library KCLS",
    "Issaquah Library KCLS",
    "Kenmore Library KCLS",
    "Kent Library KCLS",
    "Kent Panther Lake Library KCLS",
    "Kingsgate Library KCLS",
    "Kirkland Library KCLS",
    "Lake Forest Park Library KCLS",
    "Lake Hills Library KCLS",
    "Library Connection @ Crossroads",
    "Maple Valley Library KCLS",
    "Mercer Island Library KCLS",
    "Muckleshoot Library KCLS",
    "Newcastle Library KCLS",
    "Newport Way Library KCLS",
    "North Bend Library KCLS",
    "Redmond Library KCLS",
    "Renton Library KCLS",
    "Renton Highlands Library KCLS",
    "Richmond Beach Library KCLS",
    "Sammamish Library KCLS",
    "Shoreline Library KCLS",
    "Skykomish Library KCLS",
    "Skyway Library KCLS",
    "Snoqualmie Library KCLS",
    "Southcenter Library KCLS",
    "Tukwila Library KCLS",
    "Valley View Library KCLS",
    "Vashon Library KCLS",
    "White Center Library KCLS",
    "Woodinville Library KCLS",
    "Woodmont Library KCLS",
  ],

  spl: [
    "Central Library Seattle Public Library",
    "Ballard Branch Seattle Public Library",
    "Beacon Hill Branch Seattle Public Library",
    "Broadview Branch Seattle Public Library",
    "Capitol Hill Branch Seattle Public Library",
    "Columbia Branch Seattle Public Library",
    "Delridge Branch Seattle Public Library",
    "Douglass-Truth Branch Seattle Public Library",
    "Fremont Branch Seattle Public Library",
    "Green Lake Branch Seattle Public Library",
    "Greenwood Branch Seattle Public Library",
    "High Point Branch Seattle Public Library",
    "International District Chinatown Branch Seattle Public Library",
    "Lake City Branch Seattle Public Library",
    "Madrona-Sally Goldmark Branch Seattle Public Library",
    "Magnolia Branch Seattle Public Library",
    "Montlake Branch Seattle Public Library",
    "NewHolly Branch Seattle Public Library",
    "Northeast Branch Seattle Public Library",
    "Northgate Branch Seattle Public Library",
    "Queen Anne Branch Seattle Public Library",
    "Rainier Beach Branch Seattle Public Library",
    "South Park Branch Seattle Public Library",
    "Southwest Branch Seattle Public Library",
    "University Branch Seattle Public Library",
    "Wallingford Branch Seattle Public Library",
    "West Seattle Branch Seattle Public Library",
  ],

  "sno-isle": [
    "Arlington Library Sno-Isle Libraries",
    "Brier Library Sno-Isle Libraries",
    "Clinton Library Sno-Isle Libraries",
    "Coupeville Library Sno-Isle Libraries",
    "Darrington Library Sno-Isle Libraries",
    "Edmonds Library Sno-Isle Libraries",
    "Freeland Library Sno-Isle Libraries",
    // Gold Bar Library omitted — Google Places cannot disambiguate it from Sultan Library
    "Granite Falls Library Sno-Isle Libraries",
    "Lake Stevens Library Sno-Isle Libraries",
    "Langley Library Sno-Isle Libraries",
    "Lynnwood Library Sno-Isle Libraries",
    "Marysville Library Sno-Isle Libraries",
    "Mill Creek Library Sno-Isle Libraries",
    "Monroe Library Sno-Isle Libraries",
    "Mountlake Terrace Library Sno-Isle Libraries",
    "Mukilteo Library Sno-Isle Libraries",
    "Oak Harbor Library Sno-Isle Libraries",
    "Snohomish Library Sno-Isle Libraries",
    "Stanwood Library Sno-Isle Libraries",
    "Sultan Library Sno-Isle Libraries",
  ],

  everett: [
    "Everett Public Library Main Branch Everett WA",
    "Everett Public Library Evergreen Branch Everett WA",
  ],

  "pierce-county": [
    "Bonney Lake Pierce County Library",
    "Buckley Pierce County Library",
    "DuPont Pierce County Library",
    "Eatonville Pierce County Library",
    "Fife Pierce County Library",
    "Graham Pierce County Library",
    "Key Center Pierce County Library",
    "Lakewood Pierce County Library",
    "Milton Edgewood Pierce County Library",
    "Orting Pierce County Library",
    "Parkland Spanaway Pierce County Library",
    "Peninsula Pierce County Library Gig Harbor",
    "South Hill Pierce County Library",
    "Steilacoom Pierce County Library",
    "Sumner Pierce County Library",
    "Summit Pierce County Library",
    "Tillicum Pierce County Library",
    "University Place Pierce County Library",
  ],

  tacoma: [
    "Main Branch Tacoma Public Library",
    "Fern Hill Branch Tacoma Public Library",
    "Kobetich Branch Tacoma Public Library",
    // MLK Branch omitted — Google Places resolves it to Main Branch
    "Moore Branch Tacoma Public Library",
    "Mottet Branch Tacoma Public Library",
    "South Tacoma Branch Tacoma Public Library",
    "Swasey Branch Tacoma Public Library",
    "Wheelock Branch Tacoma Public Library",
  ],
};
